# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARSpaceship: # do not change this name
    color: 'blue'
    state:
      x: -9.0
      y: -9.0
      psi: 0
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      delta: 0.0
      m: 2.5
    goal:
      type: dock
      state: 
        x: 8.5
        y: 9.5
        psi: 3.3
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.1
      vel_tolerance: 0.2
      add_land_space: 0.0 
      arms_length: 1.3 
      offset: 1.3


planets:
  Namek:
    center: [5.0, 4.0]
    radius: 2.5
    satellites: {}
  Vampa:
    center: [0.0, 0.0]
    radius: 2.0
    satellites: {}

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98