# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARocket: # do not change this name
    color: 'blue'
    state:
      x: -8.0
      y: -8.0
      psi: 0.0
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
      phi: 0.0
      m: 2.5
    goal:
      type: dock
      state: 
        x: 9.5
        y: 9.5
        psi: 3.3
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.1
      vel_tolerance: 0.2

planets:
  Namek:
    center: [5.0, 4.0]
    radius: 3.0
    satellites: {}
  Yardrat:
    center: [-5.0, -4.0]
    radius: 3.0
    satellites: {}
  Vampa:
    center: [0.0, 0.0]
    radius: 2.0
    satellites: {}

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]

seed: 98