# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARSpaceship: # do not change this name
    color: 'blue'
    state:
      x: -9.0
      y: -5.0
      psi: 0.5
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
    goal:
      type: dock
      state: 
        x: 8.5
        y: 8
        psi: 3.3
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.1
      vel_tolerance: 0.2
      add_land_space: 0.0 
      arms_length: 1.3 
      offset: 1.3

planets:
  Gaia:
    center: [5, -3]
    radius: 1.5

asteroids:
  Apophis:
    start: [5.0, 5.0]
    radius: 1.0
    velocity: [-1.2, 0.0]
    orientation: 0.5
  Hercules:
    start: [-8.0, 5.0]
    radius: 1.0
    velocity: [0.0, -2.0]
    orientation: 0.0
  Eros:
    start: [10.0, 0.0]
    radius: 0.5
    velocity: [-1.0, 0.0]
    orientation: 0.0
  Platopmen:
    start: [-5, -15]
    radius: 6
    velocity: [0.0, 0.4]
    orientation: 0.0

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [11, 11]
    - [11, -11]
    - [-11, -11]
    
seed: 98