# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARSpaceship: # do not change this name
    color: 'blue'
    state:
      x: -9.0
      y: -9.0
      psi: 0
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
    goal:
      type: dock
      state: 
        x: 8.5
        y: 9.5
        psi: 3.14159
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.1
      vel_tolerance: 0.2
      add_land_space: 0.0 
      arms_length: 1.3 
      offset: 1.3


planets:
  Namek:
    center: [0.0, 0.0]
    radius: 2
    satellites: {}
  Namek2:
    center: [-6.0, 6.0]
    radius: 1
    satellites: {}
  Namek3:
    center:  [6.0, -6.0]
    radius: 1
    satellites: {}

boundary:
  corners:
    - [-12, -12]
    - [-12, 12]
    - [12, 12]
    - [12, -12]
    - [-12, -12]

seed: 98