# agents:
#   PDM4ARSpaceship: # do not change this name
#     state:
#       x: -8.0                         # EDITABLE within boundaries
#       y: -8.0                         # EDITABLE within boundaries
#       psi: 0.26179938779              # EDITABLE
#       vx: 0.0
#       vy: 0.0
#       dpsi: 0.0
#     goal:
#       type: ...                       # static or dock
#       state: 
#         x: 8.0                        # EDITABLE within boundaries
#         y: 8.0                        # EDITABLE within boundaries
#         psi: 0.0                      # EDITABLE
#         vx: 0.0
#         vy: 0.0
#         dpsi: 0.0
#       pos_tolerance: 0.3              # EDITABLE
#       dir_tolerance: 2                # EDITABLE (in rad), 2 if static
#       vel_tolerance: 0.4              # EDITABLE
#       #(if dock)
#         #add_land_space: 0.0 
#         #arms_length: 1.3 
#         #offset: 1.3
#     color: blue                       # (inside superscripts !)

# planets:                              # ALL EDITABLE: or :{} or nothing
#   Namek:
#     center: [0.0, 0.0]
#     radius: 2.0
# 
# asteroids:                            # ALL EDITABLE: or :{} or nothing
#   Apophis:
#     start: [5.0, 5.0]
#     radius: 1.0
#     velocity: [-1.2, 0.0]
#     orientation: 0.5
# 
# boundary:
# # NOTE: in src>pdm4ar>exercises_def>ex13>ex13.py, the function _ex13_vis sets the plot limits at [-12, 27], [-12, -12]: change it to visualize the animation correctly 
#  corners:                           # EDITABLE in clockwise order; last point must be equal to the first
#     - [-11, -11]
#     - [-11, 11]
#     - [11, 11]
#     - [11, -11]
#     - [-11, -11]

# seed: 98