# Test case 1 in pdm4ar_scvxx
agents:
  PDM4ARSpaceship: # do not change this name
    color: 'blue'
    state:
      x: -9.0
      y: -9.0
      psi: 0
      vx: 0.0
      vy: 0.0
      dpsi: 0.0
    goal:
      type: dock
      state: 
        x: 13.5
        y: 9
        psi: 4.71
        vx: 0.0
        vy: 0.0
        dpsi: 0.0
      pos_tolerance: 0.5
      dir_tolerance: 0.1
      vel_tolerance: 0.2
      add_land_space: 0.0 
      arms_length: 1.3 
      offset: 1.3


planets:
  Namek:
    center: [5.0, 4.0]
    radius: 1.8
    satellites: {}
  Vampa:
    center: [-2.0, -2.0]
    radius: 1.5
    satellites: {}

asteroids:
  H122-B:
    start: [10.0, -4.0]
    radius: 1.0
    velocity: [-1.4, 1.4]
    orientation: 0.0
  Amelius15:
    start: [-8, 6.0]
    radius: 1.4
    velocity: [1.1, -1.5]
    orientation: 0.0
  H122-C:
    start: [13.0, -7.0]
    radius: 0.8
    velocity: [-0.4, 0.4]
    orientation: 0.0

boundary:
  corners:
    - [-11, -11]
    - [-11, 11]
    - [16, 11]
    - [16, -11]
    - [-11, -11]

seed: 98