agents:
  PDM4AR_1:
    state:
      x: 0
      y: 10
      psi: 1
    goal: [ 4.5, -2 ]
    goal_radius: 0.5
    color: 'red'
  PDM4AR_2:
    state:
      x: -2
      y: -4
      psi: 1
    goal: [ 6,4 ]
    goal_radius: 0.5
    color: 'green'
  PDM4AR_3:
    state:
      x: -9
      y: 9
      psi: 1
    goal: [ 8,8 ]
    goal_radius: 0.5
    color: 'blue'
  PDM4AR_4:
    state:
      x: -9
      y: -9
      psi: 1
    goal: [ 10,10 ]
    goal_radius: 0.5
    color: 'saddlebrown'

static_obstacles:
  - [ [ -7, -7 ], [ -7, -3 ], [ -3, -3 ], [ -3, -7 ], [ -7, -7 ] ]
  - [ [ -1, -7 ], [ -1, -3 ], [ 3, -3 ], [ 3, -7 ], [ -1, -7 ] ]
  - [ [ 5,  -7 ], [ 5, -3 ], [ 9, -3 ], [ 9, -7 ], [ 5, -7 ] ]
  - [ [ -7, -1 ], [ -7, 3 ], [ -3, 3 ], [ -3, -1 ], [ -7, -1 ] ]
  - [ [ -1, -1 ], [ -1, 3 ], [ 3, 3 ], [ 3, -1 ], [ -1, -1 ] ]
  - [ [ 5, -1 ], [ 5, 3 ], [ 9, 3 ], [ 9, -1 ], [ 5, -1 ] ]
  - [ [ -6, 5 ], [ -5, 6 ], [ -4, 6 ], [ -5, 4 ], [ -6, 5 ] ]
  - [ [ 0, 5 ], [ 1, 7 ], [ 2, 6 ], [ 1, 4 ], [ 0, 5 ] ]
  - [ [ 6, 5 ], [ 7, 7 ], [ 8, 6 ], [ 7, 4 ], [ 6, 5 ] ]

boundary: [ [ -11, -11 ], [ -11, 11 ], [ 11, 11 ], [ 11, -11 ], [ -11, -11 ] ]

seed: 98