agents:
  PDM4ARSpaceship:
    color: blue
    goal:
      add_land_space: 0.5
      arms_length: 1.3
      dir_tolerance: 0.1
      offset: 1.8
      pos_tolerance: 0.5
      state:
        dpsi: 0.0
        psi: 3.14159
        vx: 0.0
        vy: 0.0
        x: 8.5
        y: 9.5
      type: dock
      vel_tolerance: 0.2
    state:
      delta: 0.0
      dpsi: 0.0
      m: 2.5
      psi: 0
      vx: 0.0
      vy: 0.0
      x: -9.0
      y: -9.0
boundary:
  corners:
  - - -12
    - -12
  - - -12
    - 12
  - - 12
    - 12
  - - 12
    - -12
  - - -12
    - -12
dynamics_disturbance:
  angular_acc_sigma: 0.08
  duration: 1.5
  linear_acc_sigma: 0.35
  seed: 106
  start_time: 6.0
planets:
  Namek:
    center:
    - 0.0
    - 0.0
    radius: 2
  Namek2:
    center:
    - -6.0
    - 6.0
    radius: 1
  Namek3:
    center:
    - 6.0
    - -6.0
    radius: 1
seed: 98
